version: '3.9'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $MY_DB_USER
      POSTGRES_PASSWORD: $MY_DB_PASS
      POSTGRES_DB: prodigy_api
    ports:
      - '5438:5432'
    volumes:
      - prodigy-data-vol:/var/lib/postgresql/data
      - ./db/sql/install-extensions.sql:/docker-entrypoint-initdb.d/install-extensions.sql
volumes:
  prodigy-data-vol:
